on:
  workflow_call:

name: danger

jobs:
  echo-input:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ariteset
        run: pwd && ls -al && tree -L 6 /

      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('../pr-bot.js')
            await script({github, context, core})
